"""Phase 2: Ralph Execution — iterative Claude agent loop for coding.

Replaces the former ralph.sh bash script with a pure Python implementation.
Each iteration feeds CLAUDE.md to Claude Code (--print mode) and checks for
the <promise>COMPLETE</promise> completion signal.
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path

from ralph_pipeline.ai.claude import ClaudeRunner
from ralph_pipeline.config import MilestoneConfig, PipelineConfig
from ralph_pipeline.context_refresh import refresh_context_for_bugfix
from ralph_pipeline.git_ops import GitOps
from ralph_pipeline.infra.test_runner import TestRunner
from ralph_pipeline.log import PipelineLogger
from ralph_pipeline.prd_schema import PRD, PRDLoadError
from ralph_pipeline.subprocess_utils import is_dry_run
from ralph_pipeline.usage import EventLogger

COMPLETION_SIGNAL = "<promise>COMPLETE</promise>"

RUNTIME_FOOTER_START = "\n\n<!-- RUNTIME FOOTER — auto-generated by pipeline. Do not edit. -->\n"
RUNTIME_FOOTER_END = "\n<!-- END RUNTIME FOOTER -->\n"

BUGFIX_NOTICE_START = "\n\n<!-- BUGFIX NOTICE — auto-generated by pipeline. Do not edit. -->\n"
BUGFIX_NOTICE_END = "\n<!-- END BUGFIX NOTICE -->\n"

_BUGFIX_NOTICE_BODY = """## BUGFIX MODE

> You are in **bugfix mode**. The pipeline has refreshed the Codebase Snapshot
> in `context.md`, but other sections may reference the pre-implementation state.

**Critical rules for bugfix mode:**

1. **Trust the actual codebase over context.md** — if context.md says file X
   has certain content but the file on disk differs, the file on disk is correct.
2. **Read the Bugfix Context section** in `context.md` — it contains the QA
   failure summary and a list of files changed during Phase 2.
3. **Focus on failing stories** — the PRD has `passes: false` on stories that
   need fixing, with QA notes describing what went wrong.
4. **Consult progress.txt** — it has structured per-story logs from Phase 2,
   including implementation decisions and codebase patterns discovered.
5. **Do not re-implement passing stories** — only fix what QA flagged.
"""


def _build_runtime_footer(config: PipelineConfig) -> str:
    """Build a deterministic runtime footer with test/gate commands from config.

    This ensures Ralph always has the concrete, verified quality commands
    regardless of whether the AI-generated context.md includes them.
    The footer is derived from pipeline-config.json at runtime — if the user
    updates the config, the next milestone run picks up the changes
    automatically.
    """
    lines: list[str] = []
    lines.append("## Runtime Quality Commands")
    lines.append("")
    lines.append("> Auto-injected by pipeline from pipeline-config.json.")
    lines.append("> These are the verified commands you MUST run before committing.")
    lines.append("")

    # ── Test execution commands ──
    te = config.test_execution
    has_test_cmds = False

    if te.setup_command:
        lines.append("### Test Infrastructure Setup")
        lines.append("")
        lines.append("```bash")
        if te.teardown_command:
            lines.append(f"{te.teardown_command}   # clean slate")
        lines.append(f"{te.setup_command}   # start dependency services")
        lines.append("```")
        lines.append("")

    if te.tier1.environments:
        lines.append("### Test Commands (Tier 1)")
        lines.append("")
        lines.append("```bash")
        for env in te.tier1.environments:
            lines.append(f"# {env.name}")
            if env.build_command:
                lines.append(env.build_command)
            lines.append(env.test_command)
        lines.append("```")
        lines.append("")
        has_test_cmds = True
    elif te.test_command:
        lines.append("### Test Command")
        lines.append("")
        lines.append("```bash")
        if te.build_command:
            lines.append(te.build_command)
        lines.append(te.test_command)
        lines.append("```")
        lines.append("")
        has_test_cmds = True

    if te.integration_test_command:
        lines.append("### Integration Test Command")
        lines.append("")
        lines.append("```bash")
        lines.append(te.integration_test_command)
        lines.append("```")
        lines.append("")

    # ── Gate checks ──
    if config.gate_checks.checks:
        lines.append("### Gate Checks")
        lines.append("")
        lines.append("ALL gate checks must pass before committing:")
        lines.append("")
        lines.append("```bash")
        for check in config.gate_checks.checks:
            req = "" if check.required else "  # optional"
            lines.append(f"{check.command}{req}   # {check.name}")
        lines.append("```")
        lines.append("")

    if not has_test_cmds and not config.gate_checks.checks:
        lines.append("No test or gate check commands configured.")
        lines.append("")

    return "\n".join(lines)


def _inject_runtime_footer(
    scripts_dir: Path, config: PipelineConfig, plogger: PipelineLogger
) -> None:
    """Write runtime quality commands into CLAUDE.md on disk.

    Strips any previous runtime footer (idempotent) and appends a fresh one
    built from the current PipelineConfig.
    """
    claude_md = scripts_dir / "CLAUDE.md"
    if not claude_md.exists():
        return  # _run_ralph_loop will warn about missing file

    content = claude_md.read_text()

    # Strip previous footer if present (idempotent re-runs)
    marker = RUNTIME_FOOTER_START.strip()
    if marker in content:
        idx = content.index(marker)
        content = content[:idx].rstrip()

    footer = _build_runtime_footer(config)
    content = content + RUNTIME_FOOTER_START + footer + RUNTIME_FOOTER_END

    claude_md.write_text(content)
    plogger.info("CLAUDE.md updated with runtime quality commands from config")


def _inject_bugfix_notice(
    scripts_dir: Path, plogger: PipelineLogger
) -> None:
    """Inject a bugfix mode notice into CLAUDE.md.

    Strips any previous bugfix notice (idempotent) and appends a fresh one.
    This tells Ralph to trust the codebase over stale context.md sections.
    """
    claude_md = scripts_dir / "CLAUDE.md"
    if not claude_md.exists():
        return

    content = claude_md.read_text()

    # Strip previous notice if present (idempotent)
    notice_marker = BUGFIX_NOTICE_START.strip()
    if notice_marker in content:
        idx = content.index(notice_marker)
        # Find end marker
        end_marker = BUGFIX_NOTICE_END.strip()
        end_idx = content.find(end_marker, idx)
        if end_idx != -1:
            content = content[:idx].rstrip() + content[end_idx + len(end_marker):]
        else:
            content = content[:idx].rstrip()

    # Insert before the runtime footer (if present) so footer is always last
    rt_marker = RUNTIME_FOOTER_START.strip()
    if rt_marker in content:
        idx = content.index(rt_marker)
        before = content[:idx].rstrip()
        after = content[idx:]
        content = before + BUGFIX_NOTICE_START + _BUGFIX_NOTICE_BODY + BUGFIX_NOTICE_END + after
    else:
        content = content.rstrip() + BUGFIX_NOTICE_START + _BUGFIX_NOTICE_BODY + BUGFIX_NOTICE_END

    claude_md.write_text(content)
    plogger.info("CLAUDE.md updated with bugfix mode notice")


def _remove_bugfix_notice(
    scripts_dir: Path, plogger: PipelineLogger
) -> None:
    """Remove bugfix notice from CLAUDE.md (cleanup after bugfix cycles end)."""
    claude_md = scripts_dir / "CLAUDE.md"
    if not claude_md.exists():
        return

    content = claude_md.read_text()
    notice_marker = BUGFIX_NOTICE_START.strip()
    if notice_marker not in content:
        return

    idx = content.index(notice_marker)
    end_marker = BUGFIX_NOTICE_END.strip()
    end_idx = content.find(end_marker, idx)
    if end_idx != -1:
        content = content[:idx].rstrip() + content[end_idx + len(end_marker):]
    else:
        content = content[:idx].rstrip()

    claude_md.write_text(content)
    plogger.info("Removed bugfix notice from CLAUDE.md")


def _check_all_pass(prd_path: Path) -> bool:
    """Check if all stories in PRD have passes=true."""
    try:
        data = json.loads(prd_path.read_text())
        stories = data.get("userStories", [])
        if not stories:
            return False
        return all(s.get("passes", False) for s in stories)
    except (json.JSONDecodeError, FileNotFoundError):
        return False


def _get_prd_story_count(
    prd_path: Path, plogger: PipelineLogger
) -> int | None:
    """Read the actual story count from a PRD JSON file.

    Returns the count of userStories, or None if the PRD cannot be loaded.
    """
    try:
        prd = PRD.load(prd_path)
        return prd.story_count
    except PRDLoadError as e:
        plogger.warning(f"Could not load PRD for story count: {e}")
        return None


def _resolve_iteration_budget(
    milestone: MilestoneConfig,
    config: PipelineConfig,
    project_root: Path,
    plogger: PipelineLogger,
    multiplier: int | None = None,
) -> int:
    """Compute the iteration budget for a milestone.

    Uses the PRD-derived story count when available (post-Phase 1).
    Falls back to the configured ``milestone.stories`` value.
    Emits a deprecation warning when the two counts differ.

    Args:
        milestone: The milestone config.
        config: Pipeline config.
        project_root: Project root path.
        plogger: Logger.
        multiplier: Override for the iterations-per-story multiplier.
                    Defaults to ``config.ralph.max_iterations_multiplier``.

    Returns:
        The iteration budget (story_count * multiplier).
    """
    if multiplier is None:
        multiplier = config.ralph.max_iterations_multiplier

    configured_stories = milestone.stories
    prd_path = (
        project_root / config.paths.tasks_dir / f"prd-m{milestone.id}.json"
    )
    prd_stories = _get_prd_story_count(prd_path, plogger)

    if prd_stories is not None and prd_stories != configured_stories:
        plogger.warning(
            f"Story count drift detected for M{milestone.id}: "
            f"pipeline-config.json says {configured_stories} stories, "
            f"but prd-m{milestone.id}.json contains {prd_stories} stories. "
            f"Using PRD-derived count ({prd_stories}). "
            f"The 'stories' field in pipeline-config.json is now advisory — "
            f"consider updating it to match the PRD or removing it in future."
        )

    effective_stories = prd_stories if prd_stories is not None else configured_stories
    return effective_stories * multiplier


def _setup_workspace(
    milestone: MilestoneConfig,
    config: PipelineConfig,
    git: GitOps,
    plogger: PipelineLogger,
    project_root: Path,
) -> tuple[Path, Path, str]:
    """Prepare the Ralph workspace: symlink PRD, init progress, create branch.

    Returns (scripts_dir, prd_src, branch).
    """
    scripts_dir = project_root / config.paths.scripts_dir
    tasks_dir = project_root / config.paths.tasks_dir
    slug = milestone.slug
    branch = f"ralph/m{milestone.id}-{slug}"
    prd_src = tasks_dir / f"prd-m{milestone.id}.json"

    scripts_dir.mkdir(parents=True, exist_ok=True)

    # Create symlink: .ralph/prd.json → tasks/prd-mN.json
    prd_link = scripts_dir / "prd.json"
    if prd_link.exists() or prd_link.is_symlink():
        prd_link.unlink()
    try:
        rel_path = os.path.relpath(prd_src, scripts_dir)
        prd_link.symlink_to(rel_path)
    except (ValueError, OSError):
        prd_link.symlink_to(prd_src)

    # Initialize progress.txt with structured format
    progress = scripts_dir / "progress.txt"
    progress.write_text(
        f"# Ralph Progress Log — M{milestone.id} ({slug})\n"
        f"Started: {time.strftime('%Y-%m-%dT%H:%M:%S%z')}\n"
        f"\n"
        f"---\n"
        f"\n"
        f"## Implementation Log\n"
        f"\n"
        f"<!-- Ralph appends per-story entries below as it works. -->\n"
        f"<!-- Each entry should include: story ID, what was done, files changed, -->\n"
        f"<!-- decisions made, and any deviations from the spec. -->\n"
        f"\n"
        f"---\n"
        f"\n"
        f"## Codebase Patterns\n"
        f"\n"
        f"<!-- Ralph records reusable patterns discovered during implementation. -->\n"
        f"<!-- These are extracted by the PRD Writer for future milestones. -->\n"
        f"\n"
        f"---\n"
        f"\n"
        f"## Deviations & Decisions\n"
        f"\n"
        f"<!-- Ralph records any spec deviations or implementation decisions -->\n"
        f"<!-- that the Spec Reconciler should review. -->\n"
    )

    # Commit dirty tree
    git.commit_all(f"chore: pipeline artifacts before M{milestone.id}")

    # Create or checkout milestone branch
    if git.branch_exists(branch):
        git.checkout(branch)
    else:
        git.checkout(branch, create=True)

    return scripts_dir, prd_src, branch


def _run_ralph_loop(
    claude: ClaudeRunner,
    scripts_dir: Path,
    log_dir: Path,
    max_iterations: int,
    model: str,
    milestone_id: int,
    plogger: PipelineLogger,
    event_logger: EventLogger,
) -> bool:
    """Run the iterative Ralph agent loop.

    Each iteration:
      1. Reads CLAUDE.md from scripts_dir as the prompt
      2. Invokes Claude Code (--print mode) via ClaudeRunner
      3. Checks output for COMPLETE signal
      4. Logs iteration results

    Returns True if Ralph signaled completion, False if max iterations reached.
    """
    claude_md = scripts_dir / "CLAUDE.md"
    if not claude_md.exists():
        plogger.warning(
            f"CLAUDE.md not found at {claude_md} — Ralph has no instructions to execute"
        )
        return False

    log_dir.mkdir(parents=True, exist_ok=True)

    plogger.info(f"Starting Ralph loop — max {max_iterations} iterations")

    for iteration in range(1, max_iterations + 1):
        plogger.info(f"Ralph iteration {iteration}/{max_iterations}")

        prompt = claude_md.read_text()
        iter_log = log_dir / f"ralph-iter-{iteration}.log"

        start = time.monotonic()
        try:
            result = claude.run(
                prompt=prompt,
                model=model,
                phase="ralph",
                milestone=milestone_id,
                log_file=iter_log,
            )
            output = result.output
        except Exception as e:
            plogger.warning(f"Ralph iteration {iteration} failed: {e}")
            output = ""

        duration = time.monotonic() - start

        # Check for completion signal
        if COMPLETION_SIGNAL in output:
            plogger.success(
                f"Ralph completed at iteration {iteration}/{max_iterations} "
                f"({duration:.0f}s)"
            )
            return True

        plogger.info(f"Iteration {iteration} complete ({duration:.0f}s). Continuing...")
        time.sleep(2)

    plogger.warning(
        f"Ralph reached max iterations ({max_iterations}) without completing"
    )
    return False


def run_ralph_execution(
    milestone: MilestoneConfig,
    config: PipelineConfig,
    git: GitOps,
    test_runner: TestRunner,
    plogger: PipelineLogger,
    project_root: Path,
    claude: ClaudeRunner | None = None,
    event_logger: EventLogger | None = None,
) -> None:
    """Run Ralph agent for a milestone.

    - Set up workspace (PRD symlink, progress, branch)
    - Run iterative Claude agent loop
    - Run light test suite (log only)
    """
    slug = milestone.slug
    max_iter = _resolve_iteration_budget(
        milestone, config, project_root, plogger
    )

    plogger.info(f"Phase 2 (Ralph): M{milestone.id} ({slug}), max_iter={max_iter}")

    if is_dry_run():
        plogger.info(f"[DRY RUN] Would run Ralph for M{milestone.id}")
        return

    scripts_dir, prd_src, branch = _setup_workspace(
        milestone, config, git, plogger, project_root
    )

    log_dir = project_root / ".ralph" / "logs" / f"m{milestone.id}-{slug}"

    # Inject runtime quality commands into CLAUDE.md before Ralph starts
    _inject_runtime_footer(scripts_dir, config, plogger)

    # Run the Ralph agent loop
    if claude is not None:
        _run_ralph_loop(
            claude=claude,
            scripts_dir=scripts_dir,
            log_dir=log_dir,
            max_iterations=max_iter,
            model=config.models.ralph,
            milestone_id=milestone.id,
            plogger=plogger,
            event_logger=event_logger or EventLogger(log_dir / "pipeline.jsonl"),
        )
    else:
        plogger.warning("No ClaudeRunner provided — skipping Ralph execution")

    if _check_all_pass(prd_src):
        plogger.success(f"Ralph: M{milestone.id} ALL PASS")
    else:
        plogger.warning(
            f"Ralph: M{milestone.id} completed with some stories still failing"
        )

    # Light test run after Ralph — log results for QA but don't block
    qa_dir = project_root / config.paths.qa_dir
    qa_dir.mkdir(parents=True, exist_ok=True)

    if config.test_execution.tier1.environments:
        result = test_runner.run_tier1_tests(
            f"post-ralph M{milestone.id}", log_dir=log_dir
        )
    else:
        result = test_runner.run_test_suite(
            f"post-ralph M{milestone.id}", tier=2, log_dir=log_dir
        )

    test_runner.store_results(
        result,
        qa_dir / f"test-results-post-ralph-m{milestone.id}.md",
    )


def run_ralph_bugfix(
    milestone: MilestoneConfig,
    config: PipelineConfig,
    git: GitOps,
    project_root: Path,
    plogger: PipelineLogger,
    claude: ClaudeRunner | None = None,
    event_logger: EventLogger | None = None,
    bugfix_cycle: int = 1,
    qa_report_path: Path | None = None,
) -> None:
    """Re-run Ralph in bugfix mode (shorter iteration count).

    Before the agent loop, refreshes context.md with a current codebase
    snapshot and injects a bugfix-mode notice into CLAUDE.md.
    """
    scripts_dir = project_root / config.paths.scripts_dir
    slug = milestone.slug
    max_iter = _resolve_iteration_budget(
        milestone, config, project_root, plogger, multiplier=2
    )
    branch = f"ralph/m{milestone.id}-{slug}"

    plogger.info(f"Ralph bugfix: M{milestone.id} ({slug}), max_iter={max_iter}")

    git.checkout(branch)

    # Re-link PRD
    prd_link = scripts_dir / "prd.json"
    prd_src = project_root / config.paths.tasks_dir / f"prd-m{milestone.id}.json"
    if prd_link.exists() or prd_link.is_symlink():
        prd_link.unlink()
    try:
        rel_path = os.path.relpath(prd_src, scripts_dir)
        prd_link.symlink_to(rel_path)
    except (ValueError, OSError):
        prd_link.symlink_to(prd_src)

    log_dir = project_root / ".ralph" / "logs" / f"m{milestone.id}-{slug}"

    # Refresh context.md with current codebase snapshot + bugfix context
    refresh_context_for_bugfix(
        project_root=project_root,
        config=config,
        milestone_id=milestone.id,
        cycle=bugfix_cycle,
        git=git,
        plogger=plogger,
        qa_report_path=qa_report_path,
    )

    # Inject bugfix mode notice into CLAUDE.md
    _inject_bugfix_notice(scripts_dir, plogger)

    # Inject runtime quality commands into CLAUDE.md before bugfix loop
    _inject_runtime_footer(scripts_dir, config, plogger)

    if claude is not None:
        _run_ralph_loop(
            claude=claude,
            scripts_dir=scripts_dir,
            log_dir=log_dir,
            max_iterations=max_iter,
            model=config.models.ralph,
            milestone_id=milestone.id,
            plogger=plogger,
            event_logger=event_logger or EventLogger(log_dir / "pipeline.jsonl"),
        )
    else:
        plogger.warning("No ClaudeRunner provided — skipping bugfix")
