"""Tests for context_validator — execution-time context bundle validation."""

from __future__ import annotations

from pathlib import Path

import pytest

from ralph_pipeline.config import ContextLimitsConfig
from ralph_pipeline.context_validator import (
    ContextOverflowError,
    _parse_sections,
    measure_bundle,
    truncate_bundle,
    validate_context_bundle,
)


def _make_bundle(
    tmp_path: Path, lines: int, sections: dict[str, int] | None = None
) -> Path:
    """Create a context.md with the given total line count and optional per-section sizes."""
    path = tmp_path / "context.md"
    content_lines: list[str] = ["# Context Bundle: M1 — Test", ""]

    if sections:
        for name, count in sections.items():
            content_lines.append(f"## {name}")
            content_lines.extend([f"line {i}" for i in range(count - 1)])
            content_lines.append("")
    else:
        content_lines.extend([f"content line {i}" for i in range(lines - 2)])

    path.write_text("\n".join(content_lines))
    return path


def _realistic_bundle(tmp_path: Path, line_count: int) -> Path:
    """Create a realistic context bundle with standard section headers."""
    path = tmp_path / "context.md"
    lines = [
        "# Context Bundle: M3 — User Management",
        "",
        "> Auto-generated by PRD Writer.",
        "",
    ]

    # High priority sections (small)
    lines.append("## Quality Checks")
    lines.extend(["```bash", "pytest tests/", "npm test", "```", ""])

    lines.append("## Test Infrastructure Setup")
    lines.extend(["```bash", "docker compose down", "docker compose up -d", "```", ""])

    lines.append("## Test Specifications")
    for i in range(20):
        lines.append(f"### T-3.{i:02d}: Test case {i}")
        lines.append(f"Layer: Unit | Input: data_{i} | Expected: result_{i}")
    lines.append("")

    lines.append("## Architecture Reference")
    lines.extend(["### Data Model", "CREATE TABLE users (id SERIAL);", ""])

    lines.append("## Design Reference")
    lines.extend(["### UserForm", "Standard form component.", ""])

    # Low priority sections (padded to reach target)
    lines.append("## Codebase Patterns (from previous milestones)")
    for i in range(30):
        lines.append(f"- Pattern {i}: do something useful")
    lines.append("")

    lines.append("## Codebase Snapshot")
    lines.append("### File Tree")
    lines.append("```")
    lines.extend([f"src/module_{i}.py" for i in range(20)])
    lines.append("```")
    lines.append("")
    # Pad with file contents to reach target
    remaining = line_count - len(lines)
    if remaining > 0:
        for i in range(min(remaining // 10, 50)):
            lines.append(f"### src/module_{i}.py (exists)")
            lines.append("```python")
            pad_count = min(8, remaining // 50)
            for j in range(pad_count):
                lines.append(f"def func_{j}(): pass")
            lines.append("```")
            lines.append("")

    # Final padding if still short
    while len(lines) < line_count:
        lines.append(f"# padding line {len(lines)}")

    path.write_text("\n".join(lines[:line_count]))
    return path


# ── Unit tests ───────────────────────────────────────────────────────────


class TestParsesSections:
    def test_empty_file(self):
        assert _parse_sections("") == []

    def test_single_section(self):
        text = "## Quality Checks\nline 1\nline 2"
        sections = _parse_sections(text)
        assert len(sections) == 1
        assert sections[0][0] == "Quality Checks"
        assert sections[0][1] == 0  # start
        assert sections[0][2] == 3  # end (exclusive)

    def test_multiple_sections(self):
        text = "## Section A\nline\n## Section B\nline\nline"
        sections = _parse_sections(text)
        assert len(sections) == 2
        assert sections[0] == ("Section A", 0, 2)
        assert sections[1] == ("Section B", 2, 5)


class TestMeasureBundle:
    def test_measures_lines_and_tokens(self, tmp_path: Path):
        path = _make_bundle(tmp_path, 100)
        metrics = measure_bundle(path, tokens_per_line=4.5)
        assert metrics.lines == 100
        assert metrics.tokens_est == 450
        assert metrics.path == path

    def test_measures_section_sizes(self, tmp_path: Path):
        path = _make_bundle(
            tmp_path,
            lines=50,
            sections={"Quality Checks": 10, "Codebase Snapshot": 30},
        )
        metrics = measure_bundle(path)
        assert "Quality Checks" in metrics.section_sizes
        assert "Codebase Snapshot" in metrics.section_sizes

    def test_custom_tokens_per_line(self, tmp_path: Path):
        path = _make_bundle(tmp_path, 100)
        metrics = measure_bundle(path, tokens_per_line=5.0)
        assert metrics.tokens_est == 500


class TestTruncateBundle:
    def test_truncates_lowest_priority_first(self, tmp_path: Path):
        path = _realistic_bundle(tmp_path, 200)
        limits = ContextLimitsConfig(max_lines=120, max_tokens=540)
        truncated = truncate_bundle(path, limits)
        # Should have truncated at least Codebase Snapshot (lowest priority)
        assert any("Codebase Snapshot" in s for s in truncated)

    def test_preserves_quality_checks(self, tmp_path: Path):
        path = _realistic_bundle(tmp_path, 200)
        limits = ContextLimitsConfig(max_lines=100, max_tokens=450)
        truncate_bundle(path, limits)
        content = path.read_text()
        assert "## Quality Checks" in content
        assert "pytest tests/" in content

    def test_returns_truncated_section_names(self, tmp_path: Path):
        path = _realistic_bundle(tmp_path, 200)
        limits = ContextLimitsConfig(max_lines=80, max_tokens=360)
        truncated = truncate_bundle(path, limits)
        assert isinstance(truncated, list)
        assert len(truncated) > 0


# ── Integration tests: validate_context_bundle ───────────────────────────


class TestValidateContextBundle:
    def test_missing_bundle_returns_missing(self, tmp_path: Path):
        path = tmp_path / "nonexistent.md"
        limits = ContextLimitsConfig()
        result = validate_context_bundle(path, limits)
        assert result.status == "missing"

    def test_small_bundle_returns_ok(self, tmp_path: Path):
        path = _make_bundle(tmp_path, 100)
        limits = ContextLimitsConfig(max_lines=3000, max_tokens=15000)
        result = validate_context_bundle(path, limits)
        assert result.status == "ok"
        assert result.metrics.lines == 100

    def test_warns_at_80_percent(self, tmp_path: Path):
        # 80% of 200 = 160, so 170 lines should warn but not truncate
        path = _make_bundle(tmp_path, 170)
        limits = ContextLimitsConfig(max_lines=200, max_tokens=10000, warn_pct=80.0)
        result = validate_context_bundle(path, limits)
        assert result.status == "warned"
        assert "approaching limits" in result.message

    def test_truncates_on_first_exceed(self, tmp_path: Path):
        path = _realistic_bundle(tmp_path, 250)
        limits = ContextLimitsConfig(max_lines=200, max_tokens=10000, warn_pct=80.0)
        result = validate_context_bundle(path, limits, already_truncated=False)
        assert result.status == "truncated"
        assert len(result.truncated_sections) > 0
        # After truncation, the file should be smaller
        assert result.metrics.lines <= 200

    def test_aborts_on_second_exceed(self, tmp_path: Path):
        path = _make_bundle(tmp_path, 500)
        limits = ContextLimitsConfig(max_lines=100, max_tokens=450, warn_pct=80.0)
        with pytest.raises(ContextOverflowError, match="after truncation"):
            validate_context_bundle(path, limits, already_truncated=True)

    def test_token_based_warning(self, tmp_path: Path):
        # 100 lines × 4.5 = 450 tokens; warn threshold at 80% of 500 = 400
        path = _make_bundle(tmp_path, 100)
        limits = ContextLimitsConfig(
            max_lines=5000,
            max_tokens=500,
            warn_pct=80.0,
            tokens_per_line=4.5,
        )
        result = validate_context_bundle(path, limits)
        assert result.status == "warned"


# ── Config integration ───────────────────────────────────────────────────


class TestContextLimitsConfig:
    def test_defaults(self):
        cfg = ContextLimitsConfig()
        assert cfg.max_lines == 3000
        assert cfg.max_tokens == 15000
        assert cfg.warn_pct == 80.0
        assert cfg.tokens_per_line == 4.5

    def test_custom_values(self):
        cfg = ContextLimitsConfig(
            max_lines=2000,
            max_tokens=10000,
            warn_pct=75.0,
            tokens_per_line=5.0,
        )
        assert cfg.max_lines == 2000
        assert cfg.warn_pct == 75.0

    def test_pipeline_config_includes_context_limits(self):
        from ralph_pipeline.config import PipelineConfig

        config = PipelineConfig(
            project={"name": "Test"},
            milestones=[{"id": 1, "slug": "a", "name": "A", "stories": 2}],
            context_limits={"max_lines": 2000, "max_tokens": 8000},
        )
        assert config.context_limits.max_lines == 2000
        assert config.context_limits.max_tokens == 8000

    def test_pipeline_config_default_context_limits(self):
        from ralph_pipeline.config import PipelineConfig

        config = PipelineConfig(
            project={"name": "Test"},
            milestones=[{"id": 1, "slug": "a", "name": "A", "stories": 2}],
        )
        assert config.context_limits.max_lines == 3000
        assert config.context_limits.max_tokens == 15000


# ── PRD generation integration ───────────────────────────────────────────


class TestPrdGenerationContextValidation:
    """Test that prd_generation.py correctly invokes context validation."""

    def test_domain_split_detection(self, tmp_path: Path):
        """Test that a domain-split file causes PhaseError."""

        scripts_dir = tmp_path / ".ralph"
        scripts_dir.mkdir()

        split_file = scripts_dir / "domain-split-m1.md"
        split_file.write_text(
            "# Domain Split Recommendation: M1\n\n" "Split into M1a and M1b.\n"
        )

        # The domain-split check is in run_prd_generation, but we can test
        # the existence check directly
        assert split_file.exists()
        content = split_file.read_text()
        assert "Domain Split" in content
